### ISSUE TITLE
Does not work for me

### ISSUE THREAD

**Issue by ps202** [Iazel/magento2-regenurl#2]
I have tried to run php bin/magento iazel:regenurl
Here you have  an undefined variable: `catch(\Exception $e) {
                $out->writeln("<error>$pid</error>");
            }`
But that is not a problem, I have fixed that.
The main issue is, that now all my URL-s are un-SEO-d.
I hade nice SEO urls, but now they are gone...
Am I missing something?

**Comment by ps202** [comment]
Sorry, I set the store id and now it is OK.

**Comment by iazel** [comment]
Oops, my bad for the undefined variable! I'll fix it now and happy it worked in the end :)
