### ISSUE TITLE
Url regeneration per store

### ISSUE THREAD

**Issue by marcatos** [Iazel/magento2-regenurl#5]
Hi @Iazel, great module!

I forked it because I had an issue working on a multistore case: running the script firstly for store 1 and then for store 2 I noticed that products loaded were always from the same store (1).

To solve this I commented https://github.com/Iazel/magento2-regenurl/blob/master/Iazel/RegenProductUrl/Console/Command/RegenerateProductUrlCommand.php#L77 , so I would ask you if this if clause was inteded for any other consideration I didn't do.

Thanks
S

**Comment by iazel** [comment]
As far as I remember, it was required only for the default shop, but I suppose commenting it shouldn't do any harm :+1:
